### ISSUE TITLE
Find text tool

### ISSUE THREAD

**Issue by spujol** [Slicer/SlicerLanguagePacks#32]
The "Find Text" GUI of the Language Tools module indicates the shortcut Ctrl+6 but for Mac users, the actual shortcut is "Cmd+6". Could we replace the GUI text "shortcut: Ctrl+6" with "shortcut: Ctrl+6 (Windows); Cmd+6 (Mac)"?

(Slicer 5.3-2023-06-21)
<img width="733" alt="Screenshot 2023-06-28 at 1 10 13 PM" src="https://github.com/Slicer/SlicerLanguagePacks/assets/1847492/afdd7fd2-79ec-4756-b9a5-f5e48b7cc1b1">

**Comment by lassoan** [comment]
We discussed this issue some time ago with Slicer core developers and agreed to always refer to the Control button even if on macOS the key is called Command. The reason was that adding the information everywhere that "Control is Cmd on macOS" would make the documentation harder to read and it should be common knowledge among macOS users.

We could maybe add one note on this topic in each document that we create. If you think that this would be insufficient then you can start a discussion on this on the Slicer forum to get feedback from the Slicer community.

**Comment by lassoan** [comment]
Closing this, opening a more generic issue instead: https://github.com/Slicer/SlicerLanguagePacks/issues/58
