### ISSUE TITLE
French version of Add DICOM Data module

### ISSUE THREAD

**Issue by spujol** [Slicer/SlicerLanguagePacks#78]
When loading the French version of the "Add DICOM Data" module, the module's name still appears in English in the list of modules. 

Slicer5.7.0-2024-08-23 on Mac
![Screenshot 2024-08-27 at 1 57 52 PM](https://github.com/user-attachments/assets/f5d2f3bf-cb34-40cd-b31a-d949f163f225)

**Comment by spujol** [comment]
![Bug2](https://github.com/user-attachments/assets/9e0e6aac-9b66-46b0-a51d-db369480e1bb)
The Load Button also appears in English whereas it should be in French

**Comment by mhdiop** [comment]
This issue, as the one reported in Slicer/SlicerLanguagePacks#79, has the same origin. The translation function in python sources doesn't seem to work anymore.
It's related to the [recent updates](https://github.com/Slicer/Slicer/commit/b32950134dcabff1b8ab46ebead23768e5c02a43) made in the `Base/Python/slicer/i18n.py`.
I noticed that, when retrieving the filename for context detection in the `slicer.i18n.tr` function (see [there](https://github.com/Slicer/Slicer/blob/ec338323fffbf42fe3ae67986e3b4c9eeb73ab26/Base/Python/slicer/i18n.py#L81)), the obtained filename is always `i18n.py`, instead of the one containing the source string. What made the `slicer.i18n.getContext` function return a bad context for any given string.
I could work on fixing that after the workshop.

CC : @lassoan

**Comment by lassoan** [comment]
@mhdiop @spujol I've fixed the issue that @mhdiop has found (thank you @mhdiop your investigation was very useful!) and also updated all the strings on weblate for all the components (Slicer core, CTK, SlicerIGT, ...).
